name: Insertar registros en MySQL

on:
  push:
    branches:
      - main

jobs:
  insert-records:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configurar entorno MySQL
      uses: actions/setup-mysql@v1
      with:
        mysql-version: '8.0'
        mysql-host: cualquiera123456.000webhostapp.com.MYSQL_HOST
        mysql-port: 3306
        mysql-username: prueba123456
        mysql-password: Conprueba1*
    
    - name: Clonar el repositorio
      uses: actions/checkout@v2
    
    - name: Insertar registros en la base de datos
      run: |
        mysql -h cualquiera123456.000webhostapp.com.MYSQL_HOST -P  3306  -u prueba123456 -p Conprueba1* -e "USE prueba; CREATE TABLE XXX (campo1 VARCHAR(255), campo2 VARCHAR(255), campo3 VARCHAR(255)); "
